version: '3.4'
services:
  mongodb: 
    restart: always
    environment:
    container_name: hk-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE= sponsorshiphubdb
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet  
    networks: 
      - sponsorship-network
  sponsorhship-rest-service:
      restart: always
      image: danielgomessi/sponsorshiphub
      build: ./sponsorshipHubMongo
      working_dir: /sponsorshipHubMongo
      volumes: 
        - ./sponsorshipHubMongo:/sponsorshipHubMongo
        - ~/.m2:/root/.m2
      networks: 
        - sponsorship-network
      ports: 
        - "8084:8080"
      command: mvn clean spring-boot:run
      links: 
        - mongodb
      depends_on: 
        - mongodb
networks: 
  sponsorship-network:
    driver: bridge